dist: trusty

# Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# Use APT Addon to install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# Start Xvfb so you can run headless Chrome
before_install:
  - sh -e /etc/init.d/xvfb start

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  # travis_wait is for 20 min without output
  - travis_wait 20 npm install