dist: trusty
sudo: false

addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

language: node_js
import:
  - nodejs/ci-config-travis:lts/gte-10.yml

cache:
  directories:
    - ./node_modules

#install:
#  - npm test