language: node_js
node_js:
  - "14"

# Cache node_modules
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test-headless
  - ng e2e
  - ng build