dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  # travis_wait is for 20 min without output
  - travis_wait 20 npm install